-- use {
--     'itchyny/lightline.vim',
--     setup = function()
--         vim.g.lightline = {
--             enable = {statusline = 0, tabline = 1},
--             tab = {
--                 active = {'devicon', 'filename', 'modified'},
--                 inactive = {'filename', 'modified'}
--             }
--         }
--     end
-- }
-- use {
--     'simnalamburt/vim-mundo',
--     cmd = 'MundoToggle',
--     config = function()
--         vim.g.mnudo_width = math.floor(0.2 * vim.o.columns)
--         vim.g.mundo_preview_height = math.floor(0.5 * vim.o.lines)
--         vim.g.mundo_right = 1
--         vim.cmd('augroup MUNDO')
--         vim.cmd('autocmd!')
--         vim.cmd('autocmd Filetype MundoDiff set wrap')
--         vim.cmd('augroup END')
--     end
-- }
