-- Plug("lukas-reineke/lsp-format.nvim", {
-- 	config = function()
-- 		require("lsp-format").setup({
-- 			lua = {
-- 				exclude = { "sumneko_lua" },
-- 			},
-- 		})
-- 	end,
-- })

-- Plug("hrsh7th/cmp-vsnip", { disable = true })
-- Plug("hrsh7th/vim-vsnip-integ", { disable = true })
-- Plug("hrsh7th/vim-vsnip", {
-- 	disable = true,
-- 	setup = function()
-- 		vim.g.vsnip_snippet_dir = vim.fn.stdpath("config") .. "/snippets/vsnip"
-- 	end,
-- 	config = function()
-- 		map(
-- 			"i",
-- 			"<tab>",
-- 			'vsnip#available(1) ? "<Plug>(vsnip-expand-or-jump)" : "<tab>"',
-- 			{ expr = true, remap = true }
-- 		)
-- 		map("i", "<s-tab>", 'vsnip#jumpable(-1) ? "<Plug>(vsnip-jump-prev)" : "<s-tab>"', { expr = true, remap = true })
-- 		map("s", "<tab>", 'vsnip#jumpable(1) ? "<Plug>(vsnip-jump-next)" : "<tab>"', { expr = true, remap = true })
-- 		map("s", "<s-tab>", 'vsnip#jumpable(-1) ? "<Plug>(vsnip-jump-prev)" : "<s-tab>"', { expr = true, remap = true })
-- 	end,
-- })
-- Plug("p00f/nvim-ts-rainbow", {
-- 	config = function()
-- 		local color = require("colorscheme").color
-- 		require("colorscheme").add_plug_hl({
-- 			rainbowcol1 = { fg = color.red },
-- 			rainbowcol2 = { fg = color.green },
-- 			rainbowcol3 = { fg = color.blue },
-- 			rainbowcol4 = { fg = color.yellow },
-- 			rainbowcol5 = { fg = color.cyan },
-- 			rainbowcol6 = { fg = color.magenta },
-- 			rainbowcol7 = { fg = color.orange },
-- 		})
-- 		require("nvim-treesitter.configs").setup({
-- 			rainbow = {
-- 				enable = true,
-- 				disable = {},
-- 				-- Also highlight non-bracket delimiters like html tags, boolean or table: lang -> boolean
-- 				extended_mode = true,
-- 				-- Do not enable for files with more than n lines, int
-- 				max_file_lines = nil,
-- 			},
-- 		})
-- 	end,
-- })
