--     use {
--         'hrsh7th/nvim-compe',
--         config = function()
--             vim.g.loaded_compe_treesitter = true
--             vim.g.loaded_compe_snippets_nvim = true
--             vim.g.loaded_compe_spell = true
--             vim.g.loaded_compe_tags = true
--             vim.g.loaded_compe_ultisnips = true
--             vim.g.loaded_compe_vim_lsc = true
--             vim.g.loaded_compe_vim_lsp = true
-- 
--             require('compe').setup {
--                 enabled = true,
--                 autocomplete = true,
--                 debug = false,
--                 min_length = 1,
--                 preselect = 'always',
--                 source = {
--                     path = true,
--                     buffer = true,
--                     nvim_lsp = true,
--                     nvim_lua = true,
--                     vsnip = true
--                 }
--             }
--             vim.api.nvim_exec([[
--             augroup COMPE
--                 autocmd!
--                 autocmd VimEnter * lua vim.defer_fn(function() vim.api.nvim_set_keymap('i', '<cr>', 'compe#confirm("<cr>")', {expr=true}) end, 0)
--             augroup END
--         ]], false)
--         end
--     }
-- use {
--     "ray-x/lsp_signature.nvim",
--     disable = true,
--     config = function()
--         require"lsp_signature".on_attach(
--             {
--                 bind = true, -- This is mandatory, otherwise border config won't get registered.
--                 hint_enable = false,
--                 handler_opts = {
--                     border = "double" -- double, single, shadow, none
--                 },
--                 decorator = {"`", "`"}
--             })
--     end
-- }
-- use {
--     'itchyny/lightline.vim',
--     setup = function()
--         vim.g.lightline = {
--             enable = {statusline = 0, tabline = 1},
--             tab = {
--                 active = {'devicon', 'filename', 'modified'},
--                 inactive = {'filename', 'modified'}
--             }
--         }
--     end
-- }
-- use {
--     'simnalamburt/vim-mundo',
--     cmd = 'MundoToggle',
--     config = function()
--         vim.g.mnudo_width = math.floor(0.2 * vim.o.columns)
--         vim.g.mundo_preview_height = math.floor(0.5 * vim.o.lines)
--         vim.g.mundo_right = 1
--         vim.cmd('augroup MUNDO')
--         vim.cmd('autocmd!')
--         vim.cmd('autocmd Filetype MundoDiff set wrap')
--         vim.cmd('augroup END')
--     end
-- }
