return {
	root_markers = { ".git", ".hg", ".svn", ".bzr", "_darcs", ".root" },
	"kyazdani42/nvim-web-devicons",
	"tridactyl/vim-tridactyl",
	"wsdjeg/vim-fetch",
	"farmergreg/vim-lastplace",
	"git@github.com:ipod825/vim-tabdrop",
	"RRethy/nvim-treesitter-endwise",
	"windwp/nvim-ts-autotag",
	"haringsrob/nvim_context_vt",
	"tpope/vim-abolish",
	"tami5/sqlite.lua",
	"jubnzv/virtual-types.nvim",
	{ "junegunn/fzf", build = ":call fzf#install()" },
	{ "voldikss/vim-translator", cmd = "TranslateW" },
	"onsails/lspkind.nvim",
	"ray-x/lsp_signature.nvim",
	{ "hrsh7th/cmp-nvim-lua", dependencies = { "nvim-cmp" } },
	{ "saadparwaiz1/cmp_luasnip", dependencies = { "nvim-cmp" } },
	{ "hrsh7th/cmp-nvim-lsp-signature-help", dependencies = { "nvim-cmp" } },
	{ "hrsh7th/cmp-buffer", dependencies = { "nvim-cmp" } },
	{ "hrsh7th/cmp-nvim-lsp", dependencies = { "nvim-cmp" } },
	{ "hrsh7th/cmp-path", dependencies = { "nvim-cmp" } },
	{ "hrsh7th/cmp-nvim-lua", dependencies = { "nvim-cmp" } },
	{ "hrsh7th/cmp-cmdline", dependencies = { "nvim-cmp" } },
	{ "rhysd/vim-grammarous", cmd = "GrammarousCheck" },
	"nvim-neotest/neotest",
	"nvim-neotest/neotest-plenary",
	"neovim/nvim-lspconfig",
	"majutsushi/tagbar",
	"theHamsta/nvim-dap-virtual-text",
	"machakann/vim-swap",
	"LukasPietzschmann/telescope-tabs",
	{ "will133/vim-dirdiff", cmd = "DirDiff" },
	"mrjones2014/smart-splits.nvim",
	"whiteinge/diffconflicts",
    {"git@github.com:ipod825/oldfiles.nvim", config=true},
	"andymass/vim-matchup",
	{ "AndrewRadev/linediff.vim", cmd = { "LineDiffAdd" } },
	"chrisbra/Colorizer",
	"ziontee113/color-picker.nvim",
	"rbtnn/vim-vimscript_lasterror",
}
